name: .NET Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install CMake
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes

    - name: Build SPIRV-Cross DLL
      shell: powershell
      run: |
        git clone https://github.com/KhronosGroup/SPIRV-Cross.git
        cd SPIRV-Cross
        mkdir build
        cd build
        cmake .. -DSPIRV_CROSS_SHARED=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project (Release)
      run: dotnet build --configuration Release

    - name: Copy SPIRV-Cross DLLs
      shell: powershell
      run: |
        $dllPath = "SPIRV-Cross\build\Release\spirv-cross-c-shared.dll"
        $outputDir = "bin\Release\net8.0"
        if (!(Test-Path $outputDir)) { $outputDir = "USCSandbox\bin\Release\net8.0" }
        New-Item -ItemType Directory -Path $outputDir -Force
        Copy-Item $dllPath $outputDir

    - name: Package output
      run: |
        mkdir published
        Compress-Archive -Path USCSandbox/bin/Release/net8.0/* -DestinationPath published/USCSandbox.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: USCSandbox-Build
        path: published/USCSandbox.zip
