name: .NET Windows Build

on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies (CMake, etc.)
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes

    - name: Build SPIRV-Cross DLL
      shell: powershell
      run: |
        git clone https://github.com/KhronosGroup/SPIRV-Cross.git
        cd SPIRV-Cross
        mkdir build
        cd build
        cmake .. -DSPIRV_CROSS_SHARED=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Copy SPIRV-Cross DLLs
      shell: powershell
      run: |
        $dllPath = "SPIRV-Cross\build\Release\spirv-cross-c-shared.dll"
        $outputDir = "bin\Release"
        New-Item -ItemType Directory -Path $outputDir -Force
        Copy-Item $dllPath $outputDir

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
