name: .NET Windows Build

# Run manually from GitHub UI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # Install dependencies including vcpkg and SPIRV-Cross shared DLL
    - name: Install SPIRV-Cross via vcpkg
      shell: powershell
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg install spirv-cross-c-shared:x64-windows

    # Setup .NET 8
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore .NET dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Copy SPIRV-Cross DLLs to output directory
    - name: Copy SPIRV-Cross DLLs
      shell: powershell
      run: |
        $outputDir = "bin\Release"
        New-Item -ItemType Directory -Path $outputDir -Force
        Copy-Item .\vcpkg\installed\x64-windows\bin\spirv-cross-c-shared.dll $outputDir

    # Run tests
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
